import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const client=await readFile('public/assets/site.js','utf8');
const form=(await readFile('src/partials/form.html','utf8')).replaceAll('{{FORM_KIND}}','stairs');
function page(options={}){const dom=new JSDOM('<!doctype html><body>'+form+'<button data-cookie-settings>Settings</button></body>',{url:options.url||'https://tolgyalapanyag.hu/lepcso?utm_source=facebook&utm_campaign=stairs',runScripts:'outside-only'});const w=dom.window;w.SZOMEX_CONFIG={trackingEnabled:true,gaId:'G-5W1XXG6H15',adsId:'AW-16959665415',adsLeadLabel:'wGcRCIuopNIaEIfq_5Y_',metaPixelId:'1234567890',clarityId:'rf8y3ss130',...options.config};w.AbortSignal=AbortSignal;if(options.consent)w.localStorage.setItem('szomex-consent-v1',JSON.stringify({...options.consent,expires:Date.now()+100000}));for(const [k,v] of Object.entries(options.session||{}))w.sessionStorage.setItem(k,v);w.eval(client);return dom;}
const events=d=>d.window.dataLayer.filter(a=>a[0]==='event');
const leadEvents=d=>({ga:events(d).filter(a=>a[1]==='generate_lead').length,legacy:events(d).filter(a=>a[1]==='form_bekuldes').length,ads:events(d).filter(a=>a[1]==='conversion').length,meta:(d.window.fbq?.queue||[]).filter(a=>a[1]==='Lead').length});
const thankYou='https://tolgyalapanyag.hu/koszonooldal';
const receipt=(patch={})=>JSON.stringify({id:'lead-test',type:'stairs',path:'/lepcso',at:Date.now(),...patch});
test('no optional vendor is requested before consent or after rejecting',()=>{const d=page(),doc=d.window.document;assert.equal(doc.querySelectorAll('script[src]').length,0);doc.querySelector('[data-choice=reject]').click();assert.equal(doc.querySelectorAll('script[src]').length,0);assert.equal(d.window.sessionStorage.getItem('szomex-attribution'),null);d.window.close();});
test('analytics-only choice loads GA and Clarity, not Meta or the legacy container',()=>{const d=page(),doc=d.window.document;doc.querySelector('[data-choice=settings]').click();doc.querySelector('[name=analytics]').checked=true;doc.querySelector('[data-choice=settings]').click();assert.ok(doc.querySelector('#google'));assert.ok(doc.querySelector('#clarity'));assert.equal(doc.querySelector('#meta'),null);assert.equal(doc.querySelector('#legacy-gtm'),null);d.window.close();});
test('accepting repeatedly cannot double-load tags',()=>{const d=page(),doc=d.window.document;doc.querySelector('[data-choice=accept]').click();doc.querySelector('[data-cookie-settings]').click();doc.querySelector('[data-choice=accept]').click();assert.equal(doc.querySelectorAll('#google').length,1);assert.equal(doc.querySelectorAll('#meta').length,1);assert.equal(d.window.fbq.queue.filter(a=>a[0]==='track'&&a[1]==='PageView').length,1);d.window.close();});
test('marketing consent configures the Google Ads tag on every page like the original site',()=>{const d=page({consent:{analytics:false,marketing:true}});assert.ok(d.window.dataLayer.some(a=>a[0]==='config'&&a[1]==='AW-16959665415'));assert.ok(!d.window.dataLayer.some(a=>a[0]==='config'&&a[1]==='G-5W1XXG6H15'));d.window.close();});
test('Google Ads click IDs stay in the GA4 page_location, other query data does not',()=>{const d=page({url:'https://tolgyalapanyag.hu/lepcso?gclid=Cj0KCQ_test-123&utm_source=google&email=person@example.com',consent:{analytics:true,marketing:true}});const config=d.window.dataLayer.find(a=>a[0]==='config'&&a[1]==='G-5W1XXG6H15');const url=new URL(config[2].page_location);assert.equal(url.searchParams.get('gclid'),'Cj0KCQ_test-123');assert.equal(url.searchParams.get('utm_source'),'google');assert.equal(url.searchParams.get('email'),null);d.window.close();});
test('preview suppresses tags even with saved consent',()=>{const d=page({consent:{analytics:true,marketing:true},config:{trackingEnabled:false}});assert.equal(d.window.document.querySelectorAll('script[src]').length,0);d.window.close();});
test('direct thank-you visits cannot create Lead or form_bekuldes conversions',()=>{const d=page({url:thankYou,consent:{analytics:true,marketing:true}});assert.deepEqual(leadEvents(d),{ga:0,legacy:0,ads:0,meta:0});d.window.close();});
async function submit(d,ok){const w=d.window,doc=w.document,f=doc.querySelector('form');f.elements.name.value='Teszt Elek';f.elements.email.value='test@example.com';f.elements.message.value='Tölgyfa lépcső alapanyagot keresek.';f.elements.privacy.checked=true;f.elements.materialOnly.checked=true;let captured;w.fetch=async(url,options)=>{captured={url,payload:JSON.parse(options.body)};return {ok,json:async()=>ok?{ok:true,id:'lead-test'}:{ok:false,message:'Szolgáltatás nem elérhető.'}};};f.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(resolve=>setTimeout(resolve,10));return captured;}
test('an accepted enquiry leaves a receipt for the thank-you page and sends no PII to tags',async()=>{const d=page({consent:{analytics:true,marketing:true}});const captured=await submit(d,true);assert.equal(captured.url,'/api/lead');assert.equal(captured.payload.attribution.utm_source,'facebook');const stored=JSON.parse(d.window.sessionStorage.getItem('szomex-receipt'));assert.equal(stored.id,'lead-test');assert.equal(stored.type,'stairs');assert.equal(stored.path,'/lepcso');assert.deepEqual(leadEvents(d),{ga:0,legacy:0,ads:0,meta:0});assert.ok(!JSON.stringify(d.window.dataLayer).includes('test@example.com'));d.window.close();});
test('the thank-you page converts once per accepted enquiry on every channel, reloads do not',()=>{const d=page({url:thankYou,consent:{analytics:true,marketing:true},session:{'szomex-receipt':receipt()}});assert.deepEqual(leadEvents(d),{ga:1,legacy:1,ads:1,meta:1});const ads=events(d).find(a=>a[1]==='conversion');assert.equal(ads[2].send_to,'AW-16959665415/wGcRCIuopNIaEIfq_5Y_');assert.equal(ads[2].transaction_id,'lead-test');const lead=events(d).find(a=>a[1]==='generate_lead');assert.equal(lead[2].page_path,'/lepcso');assert.equal(d.window.sessionStorage.getItem('szomex-receipt'),null);d.window.close();const reload=page({url:thankYou,consent:{analytics:true,marketing:true}});assert.deepEqual(leadEvents(reload),{ga:0,legacy:0,ads:0,meta:0});reload.window.close();});
test('a receipt waits for consent given on the thank-you page, and each channel fires once',()=>{const d=page({url:thankYou,session:{'szomex-receipt':receipt()}}),doc=d.window.document;assert.deepEqual(leadEvents(d),{ga:0,legacy:0,ads:0,meta:0});doc.querySelector('[data-choice=settings]').click();doc.querySelector('[name=analytics]').checked=true;doc.querySelector('[data-choice=settings]').click();assert.deepEqual(leadEvents(d),{ga:1,legacy:1,ads:0,meta:0});assert.ok(d.window.sessionStorage.getItem('szomex-receipt'));doc.querySelector('[data-cookie-settings]').click();doc.querySelector('[data-choice=accept]').click();assert.deepEqual(leadEvents(d),{ga:1,legacy:1,ads:1,meta:1});assert.equal(d.window.sessionStorage.getItem('szomex-receipt'),null);d.window.close();});
test('a stale receipt never converts',()=>{const d=page({url:thankYou,consent:{analytics:true,marketing:true},session:{'szomex-receipt':receipt({at:Date.now()-31*60000})}});assert.deepEqual(leadEvents(d),{ga:0,legacy:0,ads:0,meta:0});assert.equal(d.window.sessionStorage.getItem('szomex-receipt'),null);d.window.close();});
test('rejected delivery retains input, allows retry and leaves no receipt',async()=>{const d=page({consent:{analytics:true,marketing:true}});await submit(d,false);const doc=d.window.document;assert.equal(doc.querySelector('[name=email]').value,'test@example.com');assert.equal(doc.querySelector('[type=submit]').disabled,false);assert.equal(d.window.sessionStorage.getItem('szomex-receipt'),null);assert.ok(!d.window.fbq.queue.some(a=>a[1]==='Lead'));assert.match(doc.querySelector('.form-status').textContent,/nem elérhető/);d.window.close();});
test('form remains usable with all measurement rejected; campaign source is sent but not stored',async()=>{const d=page({url:'https://tolgyalapanyag.hu/lepcso?utm_source=facebook&utm_campaign=stairs&fbclid=IwAR_test',consent:{analytics:false,marketing:false}});const captured=await submit(d,true);assert.deepEqual(captured.payload.attribution,{utm_source:'facebook',utm_campaign:'stairs',click_source:'meta_ads'});assert.equal(d.window.sessionStorage.getItem('szomex-attribution'),null);assert.equal(d.window.document.querySelectorAll('script[src]').length,0);assert.match(d.window.document.querySelector('.form-status').textContent,/fogadtuk/);d.window.close();});
test('the timeline select offers every answer as a real option',()=>{const d=page(),options=[...d.window.document.querySelectorAll('[name=timeline] option')].map(o=>o.textContent);assert.deepEqual(options,['Válassz időpontot','Amint lehetséges','1–3 hónapon belül','3 hónapnál később','Még tervezek']);d.window.close();});
test('browsers without crypto.randomUUID still send a valid v4 request id',async()=>{const dom=new JSDOM('<!doctype html><body>'+form+'</body>',{url:'https://tolgyalapanyag.hu/lepcso',runScripts:'outside-only'});const w=dom.window;w.SZOMEX_CONFIG={trackingEnabled:false};w.AbortSignal=AbortSignal;Object.defineProperty(w,'crypto',{value:{getRandomValues:a=>globalThis.crypto.getRandomValues(a)}});w.eval(client);const captured=await submit(dom,true);assert.match(captured.payload.requestId,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);dom.window.close();});
