import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const client=await readFile('public/assets/site.js','utf8');
const form=(await readFile('src/partials/form.html','utf8')).replaceAll('{{FORM_KIND}}','stairs');
function page(options={}){const dom=new JSDOM('<!doctype html><body>'+form+'<button data-cookie-settings>Settings</button></body>',{url:options.url||'https://tolgyalapanyag.hu/lepcso?utm_source=facebook&utm_campaign=stairs',runScripts:'outside-only'});const w=dom.window;w.SZOMEX_CONFIG={trackingEnabled:true,gaId:'G-5W1XXG6H15',adsId:'AW-16959665415',adsLeadLabel:'wGcRCIuopNIaEIfq_5Y_',metaPixelId:'1234567890',clarityId:'rf8y3ss130',...options.config};w.AbortSignal=AbortSignal;if(options.consent)w.localStorage.setItem('szomex-consent-v1',JSON.stringify({...options.consent,expires:Date.now()+100000}));w.eval(client);return dom;}
test('no optional vendor is requested before consent or after rejecting',()=>{const d=page(),doc=d.window.document;assert.equal(doc.querySelectorAll('script[src]').length,0);doc.querySelector('[data-choice=reject]').click();assert.equal(doc.querySelectorAll('script[src]').length,0);assert.equal(d.window.sessionStorage.getItem('szomex-attribution'),null);d.window.close();});
test('analytics-only choice loads GA and Clarity, not Meta or the legacy container',()=>{const d=page(),doc=d.window.document;doc.querySelector('[data-choice=settings]').click();doc.querySelector('[name=analytics]').checked=true;doc.querySelector('[data-choice=settings]').click();assert.ok(doc.querySelector('#google'));assert.ok(doc.querySelector('#clarity'));assert.equal(doc.querySelector('#meta'),null);assert.equal(doc.querySelector('#legacy-gtm'),null);d.window.close();});
test('accepting repeatedly cannot double-load tags',()=>{const d=page(),doc=d.window.document;doc.querySelector('[data-choice=accept]').click();doc.querySelector('[data-cookie-settings]').click();doc.querySelector('[data-choice=accept]').click();assert.equal(doc.querySelectorAll('#google').length,1);assert.equal(doc.querySelectorAll('#meta').length,1);assert.equal(d.window.fbq.queue.filter(a=>a[0]==='track'&&a[1]==='PageView').length,1);d.window.close();});
test('preview suppresses tags even with saved consent',()=>{const d=page({consent:{analytics:true,marketing:true},config:{trackingEnabled:false}});assert.equal(d.window.document.querySelectorAll('script[src]').length,0);d.window.close();});
test('direct thank-you visits cannot create Lead or form_bekuldes conversions',()=>{const d=page({url:'https://tolgyalapanyag.hu/koszonooldal',consent:{analytics:true,marketing:true}});assert.ok(!d.window.dataLayer.some(a=>a[0]==='event'&&['generate_lead','form_bekuldes','conversion'].includes(a[1])));assert.ok(!d.window.fbq.queue.some(a=>a[1]==='Lead'));d.window.close();});
async function submit(d,ok){const w=d.window,doc=w.document,f=doc.querySelector('form');f.elements.name.value='Teszt Elek';f.elements.email.value='test@example.com';f.elements.message.value='Tölgyfa lépcső alapanyagot keresek.';f.elements.privacy.checked=true;f.elements.materialOnly.checked=true;let captured;w.fetch=async(url,options)=>{captured={url,payload:JSON.parse(options.body)};return {ok,json:async()=>ok?{ok:true,id:'lead-test'}:{ok:false,message:'Szolgáltatás nem elérhető.'}};};f.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(resolve=>setTimeout(resolve,10));return captured;}
test('accepted email triggers one Lead and legacy event without PII',async()=>{const d=page({consent:{analytics:true,marketing:true}});const captured=await submit(d,true);assert.equal(captured.url,'/api/lead');assert.equal(captured.payload.attribution.utm_source,'facebook');const events=d.window.dataLayer.filter(a=>a[0]==='event');assert.equal(events.filter(a=>a[1]==='generate_lead').length,1);assert.equal(events.filter(a=>a[1]==='form_bekuldes').length,1);assert.equal(d.window.fbq.queue.filter(a=>a[1]==='Lead').length,1);assert.ok(!JSON.stringify(events).includes('test@example.com'));d.window.close();});
test('rejected delivery retains input, allows retry and emits no Lead',async()=>{const d=page({consent:{analytics:true,marketing:true}});await submit(d,false);const doc=d.window.document;assert.equal(doc.querySelector('[name=email]').value,'test@example.com');assert.equal(doc.querySelector('[type=submit]').disabled,false);assert.ok(!d.window.fbq.queue.some(a=>a[1]==='Lead'));assert.match(doc.querySelector('.form-status').textContent,/nem elérhető/);d.window.close();});
test('form remains usable with all measurement rejected',async()=>{const d=page({consent:{analytics:false,marketing:false}});const captured=await submit(d,true);assert.deepEqual(captured.payload.attribution,{});assert.equal(d.window.document.querySelectorAll('script[src]').length,0);assert.match(d.window.document.querySelector('.form-status').textContent,/fogadtuk/);d.window.close();});
